name: Prepare Release

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Version to bump
        options:
          - minor
          - major
jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run bump version script
        run: ./scripts/bump-version.sh ${{ github.event.inputs.name }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: |
            [skip ci] Prepare the release (`${{ env.NEW_VERSION }}`)
          body: Prepare the release (`${{ env.NEW_VERSION }}`) by bumping version in code.
          commit-message: Bump library version to ${{ env.NEW_VERSION }}-SNAPSHOT
          branch: prepare-release/${{ env.NEW_VERSION }}
