name: Publish Snapshot to Sonatype repository

on:
  push:
    branches: [ "main" ]

env:
  ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
  ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

concurrency:
  group: "snapshot"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish default variant to Sonatype Snapshot repository
        run: ./gradlew publishAllPublicationsToSonatypeSnapshotRepository
      - name: Publish korlibs variant to Sonatype Snapshot repository
        run: ./gradlew publishAllPublicationsToSonatypeSnapshotRepository -Pvariant=korlibs
      - name: Publish ktor2 variant to Sonatype Snapshot repository
        run: ./gradlew publishAllPublicationsToSonatypeSnapshotRepository -Pvariant=ktor2
      - name: Publish okio variant to Sonatype Snapshot repository
        run: ./gradlew publishAllPublicationsToSonatypeSnapshotRepository -Pvariant=okio
