name: Release Library

on:
  workflow_dispatch:

env:
  ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
  ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
  ORG_GRADLE_PROJECT_isRelease: true

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Setup jq
        uses: dcarbone/install-jq-action@v3

      - name: Publish artifact to Sonatype Repository
        id: publish
        run: ./gradlew publishAllPublicationsToSonatypeRepository

      - name: Notify Sonatype Central to process artifacts
        run: |
          curl -X POST \
            -H "Authorization: Basic $(echo -n '${{ secrets.SONATYPE_USERNAME }}:${{ secrets.SONATYPE_PASSWORD }}' | base64)" \
            -H "Content-Type: application/json" \
            https://central.sonatype.com/api/v1/publisher/manual/upload/defaultRepository/dev.burnoo

      - name: Extract version from build.gradle.kts
        id: extract_version
        run: |
          version=$(sed -n 's/.*version = "\([0-9.]*\).*/\1/p' kspoon/build.gradle.kts)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.TOKEN_RELEASES }}
          tag: ${{ env.VERSION }}
          commit: ${{ github.sha }}
          generateReleaseNotes: true
          makeLatest: true
